version: "3.7"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: db
    tty: true
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: test123456
    ports:
      - "5433:5432"
    volumes:
      - data_blog:/var/lib/postgresql/data/
    networks:
      - data_blog_network

networks:
  data_blog_network:
    driver: bridge

volumes:
  data_blog: